---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "dotnet-sdk"
    directory: "/vxml-interpreter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/vxml-interpreter"
    schedule:
      interval: "daily"